Electronique_Labo/Controllers/ExpirimentController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net.Mime;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Electronique_Labo.Models;
using Microsoft.AspNet.Identity;
using static System.Net.Mime.MediaTypeNames;

namespace Electronique_Labo
{
    [Authorize]
    public class ExpirimentController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Expiriment
        public ActionResult Index()
        {
            var IdUser = User.Identity.GetUserId();
            var Vn = new ViewModel
            {
                Expiriments = db.Expiriments.Where(s=>s.ApplicationUserId== IdUser).ToList(),
                Niveaus = db.Niveaus.ToList()
            };
            return View(Vn);
        }

        public ActionResult Create()
        {
            var vm = new ViewModel()
            {
                Niveaus = db.Niveaus.ToList(),
                Filliers = db.Filliers.ToList(),
                Secteurs = db.Secteurs.ToList()
            };

            return View(vm);
        }

        [HttpPost]
        public ActionResult Create(ViewModel VN, HttpPostedFileBase ImageeExPrincipale, string[] Outildata, string[] ConseilData, IEnumerable<HttpPostedFileBase> UploadImage, List<string> UploadTitle, IEnumerable<HttpPostedFileBase> UploadDrive, List<string> UploadTitleDrive)
        {
            if (ModelState.IsValid)
            {
                //Ajouter Expiriment----------------------------------------------
                var ImageExprirmentPath = Path.Combine(Server.MapPath("~/Images/ImageExpiriment"), ImageeExPrincipale.FileName);
                ImageeExPrincipale.SaveAs(ImageExprirmentPath);
                VN.Expiriment.ApplicationUserId = User.Identity.GetUserId();
                VN.Expiriment.DateTime = DateTime.Now;
                VN.Expiriment.Image = ImageeExPrincipale.FileName;
                VN.Expiriment.IdFilliere = string.Join(",", VN.Expiriment.SelectedArrayFilliere);
                db.Expiriments.Add(VN.Expiriment);
                db.SaveChanges();
                //------------------------------Ajouter Outils--------------------------------------

                OutilConseilImage.SaveOutil(Outildata, VN.Expiriment.Id);

                //------------------------------Ajouter Conseil--------------------------------------

                OutilConseilImage.SaveConseil(ConseilData, VN.Expiriment.Id);

                //Ajouter Image----------------------------------------------------------------------
                OutilConseilImage.saveImage(UploadImage, UploadTitle, VN.Expiriment.Id);
                //Ajouter Fichier pour telecharger
                GoogleDriveFilesRepository.FileUpload(UploadDrive, UploadTitleDrive, VN.Expiriment.Id);

                return RedirectToAction("Index");
            }

            return View();
        }
        public ActionResult Edit(int? id)
        {
           
            if (id == null)
            {
                return HttpNotFound();
            }
            var exp = db.Expiriments.Find(id);
            if (exp == null)
            {
                return HttpNotFound();
            }
            var vm = new ViewModel();      
            vm.Niveaus = db.Niveaus.ToList();
            vm.Filliers = db.Filliers.ToList();
            vm.Secteurs = db.Secteurs.ToList();
            vm.Outils = db.Outils.Where(s => s.ExpirimentId == id).ToList();
            vm.Conseils = db.Conseils.Where(s => s.ExpirimentId == id).ToList();
            vm.Imageses = db.Imageses.Where(s => s.ExpirimentId == id).ToList();
            vm.GoogleDriveFiles = db.GoogleDriveFiles.Where(s => s.ExpirimentId == id).ToList();
            vm.Expiriment = exp;
            vm.Expiriment.SelectedArrayFilliere= exp.IdFilliere.Split(',').ToArray();

            return View(vm);
        }

        [HttpPost]
        public ActionResult Edit(ViewModel viewModel, HttpPostedFileBase EditImage, string[] Outildata, string[] ConseilData,List<string> UpdateImage, IEnumerable<HttpPostedFileBase> UploadImage, List<string> UploadTitle)
        {
            string oldImage = Path.Combine(Server.MapPath("~/Images/ImageExpiriment"), viewModel.Expiriment.Image);
            if (EditImage != null)
            {
                System.IO.File.Delete(oldImage);
                var ImageExprirmentPath = Path.Combine(Server.MapPath("~/Images/ImageExpiriment"), EditImage.FileName);
                EditImage.SaveAs(ImageExprirmentPath);
                viewModel.Expiriment.Image = EditImage.FileName;
            }
            viewModel.Expiriment.IdFilliere = string.Join(",", viewModel.Expiriment.SelectedArrayFilliere);
            viewModel.Expiriment.DateTime = DateTime.Now;
            db.Entry(viewModel.Expiriment).State = EntityState.Modified;
            db.SaveChanges();
            // Update Outils --------------------------------------------
      
            var outils = db.Outils.ToList();
            outils = outils.Where(s => s.ExpirimentId == viewModel.Expiriment.Id).ToList();
            db.Outils.RemoveRange(outils);
            db.SaveChanges();
            OutilConseilImage.SaveOutil(Outildata, viewModel.Expiriment.Id);

            //Update Conseil------------------------------------------
            var Conseil = db.Conseils.ToList();
            Conseil = Conseil.Where(s => s.ExpirimentId == viewModel.Expiriment.Id).ToList();
            db.Conseils.RemoveRange(Conseil);
            OutilConseilImage.SaveConseil(ConseilData, viewModel.Expiriment.Id);
            //Update Groups Image-----------------------------------------------------------------------
            var list = db.Imageses.Where(s => s.ExpirimentId == viewModel.Expiriment.Id).ToList();
            db.Imageses.RemoveRange(list);
            if (UpdateImage != null) {
                var GroupsImage = UpdateImage.ToList();
          
                db.SaveChanges();
                foreach (var img in GroupsImage)
                {
                    var images = new Images
                    {
                        Image = img,
                        ExpirimentId = viewModel.Expiriment.Id
                    };
                    db.Imageses.Add(images);
                    db.SaveChanges();
                }
            }
            OutilConseilImage.saveImage(UploadImage, UploadTitle, viewModel.Expiriment.Id);

            //Update Google Drive
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            var Expiriment = db.Expiriments.Find(id);
            db.Expiriments.Remove(Expiriment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult GetExpiriment(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            var exp = db.Expiriments.Find(id);
            if (exp == null)
            {
                return HttpNotFound();
            }
            var ImageUser = exp.ApplicationUserId;
            var vm = new ViewModel();
            vm.Niveaus = db.Niveaus.ToList();
            vm.Filliers = db.Filliers.ToList();
           
            vm.Niveau = db.Niveaus.Single(s => s.Id == exp.NiveauId);
            vm.Secteur = db.Secteurs.Single(s=>s.Id== exp.SecteurId);
            vm.Outils = db.Outils.Where(s => s.ExpirimentId == id).ToList();
            vm.Conseils = db.Conseils.Where(s => s.ExpirimentId == id).ToList();
            vm.Imageses = db.Imageses.Where(s => s.ExpirimentId == id).ToList();
            vm.GoogleDriveFiles = db.GoogleDriveFiles.Where(s => s.ExpirimentId == id).ToList();
            vm.Profileimg = db.Profileimgs.Single(s => s.ApplicationUserId == ImageUser);
            vm.Expiriment = exp;
            vm.Expiriment.SelectedArrayFilliere = exp.IdFilliere.Split(',').ToArray();

            return View(vm);
        }
        public ActionResult MyExpSearch(int? id,string title)
        {
            var IdUser = User.Identity.GetUserId();
            //listerecherche.Where(s => s.Nom_Produit.IndexOf(txtrecherche.Text, StringComparison.CurrentCultureIgnoreCase) != -1).ToList();
            var Vn = new ViewModel();
            if (title == null)
            {
                Vn.Expiriments = db.Expiriments.Where(s => s.ApplicationUserId == IdUser).ToList()
                    .Where(s => s.NiveauId == id).ToList();
            }
            else
            {
                if (id == null)
                {
                    Vn.Expiriments = db.Expiriments.Where(s => s.ApplicationUserId == IdUser).ToList()
                        .Where(s => s.Titre.IndexOf(title, StringComparison.CurrentCultureIgnoreCase) != -1).ToList();
                }
                else
                {
                    Vn.Expiriments = db.Expiriments.Where(s => s.ApplicationUserId == IdUser).ToList()
                        .Where(s => s.NiveauId == id).ToList()
                        .Where(s => s.Titre.IndexOf(title, StringComparison.CurrentCultureIgnoreCase) != -1).ToList();


                }
            }
            Vn.Niveaus = db.Niveaus.ToList();
            return View("Index",Vn);
        }
        //*gsfsgfgdfgdfgdfgdfg*/
        public ActionResult toutsearch( string title)
        {
           
            var vm = new ViewModel()
            {
                 Expiriments = db.Expiriments.Where(s => s.Titre.Contains(title)).ToList()

        };
            return View( vm);
        }
        //Favorite Controller

        public ActionResult Addtofavorite(int id)
        {

            var userId = User.Identity.GetUserId();
            

Electronique_Labo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Electronique_Labo.Models;

namespace Electronique_Labo.Controllers
{
    public class HomeController : Controller
    {
        ApplicationDbContext db=new ApplicationDbContext();
        public ActionResult Index()
        {
            var vm = new ViewModel()
            {
                Expiriments = db.Expiriments.ToList()
            };
            return View(vm);
        }
        //dffdfdsfdsfs
        public ActionResult chimie()
        {
            var vm = new ViewModel()
            {
                Expiriments = db.Expiriments.ToList()
            };
            return View("chimie",vm);
        }
        //dffdfdsfdsfs
        public ActionResult science()
        {
            var vm = new ViewModel()
            {
                Expiriments = db.Expiriments.ToList()
            };
            return View("Science",vm);
        }
        //dffdfdsfdsfs
        public ActionResult physic()
        {
            var vm = new ViewModel()
            {
                Expiriments = db.Expiriments.ToList()
            };
            return View("physic",vm);
        }
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        
    }
}

Electronique_Labo/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Electronique_Labo/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Electronique_Labo/Views/Home/Index.cshtml
@model Electronique_Labo.Models.ViewModel
﻿</div>
<body style="max-width: 100%; padding-top:0;">
    <div style="margin-top:-25px">

        @if (Request.IsAuthenticated)
        {
            <div class="card " style="width: 100%; height: 600px;margin-bottom: 70px">
                <h3 class="card-header text-primary text-center"><b> en rejoignant elabo, vous obtiendrez l'experience de personnalisation complete</b></h3>
                <img style="height: 100%; width: 100%; display: block;"
                     src="~/profileimage/animation-flat-line-knowledge-and-creative-education-graphic-design-flat-creativity-school-and-stationary-sign-and-symbol-education-icon-with-isolated-background.png" alt="Card image">
            </div>

        }
        else
        {<div class="card " style="width: 100%; height: 600px;margin-bottom: 130px">
                <h3 class="card-header text-primary text-center"><b> en rejoignant elabo, vous obtiendrez l'experience de personnalisation complete</b></h3>
                <img style="height: 100%; width: 100%; display: block;"
                     src="~/profileimage/animation-flat-line-knowledge-and-creative-education-graphic-design-flat-creativity-school-and-stationary-sign-and-symbol-education-icon-with-isolated-background.png" alt="Card image">
                <div class="card-footer">
                    <p class="card-text">
                        <h5> <p class="text-lg-center font-weight-bold">Vous n'avez pas de compte? <a onclick="fnt()" class="text-info " id="test1" href="#"><b>inscrire vous</b></a></p></h5>
                </div>
            </div>
        }


    </div>
    <fieldset style="text-align: center">
        <legend class="border-bottom border-primary"><b class="text-primary"> Science Expirimental</b></legend>
    </fieldset>
    <div class="slide  " style="margin-left: 235px;margin-right: 235px">
        @foreach (var v in Model.Expiriments)
        {
            if (v.SecteurId == 1)
            {

                <div>
                    <div class="card mr-lg-5 ml-5 ">
                        <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x225]"
                             style="height: 225px; width: 100%; display: block;" src="~/Images/ImageExpiriment/@v.Image" data-holder-rendered="true">
                        <div class="card-body">
                            <h3>@v.Titre</h3>
                            <p class="card-text">@v.DateTime</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    @Html.ActionLink("Afficher", "GetExpiriment", "Expiriment", new { id = v.Id }, new { @class = "btn btn-primary" })
                                    @Html.ActionLink(" + Favorite", "Addtofavorite", "Expiriment", new { id = v.Id }, new { @class = "btn btn-warning  " })
                                </div>
                                <small class="text-muted">@v.DateTime</small>
                            </div>
                        </div>
                    </div>
                </div>
            }
        }
    </div>
    <fieldset style="text-align: center">
        <legend class="border-bottom border-warning"><b class="text-warning"> Chimie</b></legend>
    </fieldset>
    <div class="slide  " style="margin-left: 235px;margin-right: 235px">
        @foreach (var v in Model.Expiriments)
        {
            if (v.SecteurId == 2)
            {

                <div>
                    <div class="card mr-lg-5 ml-5 ">
                        <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x225]"
                             style="height: 225px; width: 100%; display: block;" src="~/Images/ImageExpiriment/@v.Image" data-holder-rendered="true">
                        <div class="card-body">
                            <h3>@v.Titre</h3>
                            <p class="card-text">@v.But</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    @Html.ActionLink("Afficher", "GetExpiriment", "Expiriment", new { id = v.Id }, new { @class = "btn btn-primary" })
                                    @Html.ActionLink("Favorite", "Addtofavorite", "Expiriment", new { id = v.Id }, new { @class = "btn btn-warning" })
                                </div>
                                <small class="text-muted">@v.DateTime</small>
                            </div>
                        </div>
                    </div>
                </div>
            }
        }
    </div>
    <fieldset style="text-align: center">
        <legend class="border-bottom  border-success"><b class="text-success"> physique</b></legend>
    </fieldset>
    <div class="slide  " style="margin-left: 235px;margin-right: 235px">
        @foreach (var v in Model.Expiriments)
        {
            if (v.SecteurId == 3)
            {

                <div>
                    <div class="card mr-lg-5 ml-5 ">
                        <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x225]"
                             style="height: 225px; width: 100%; display: block;" src="~/Images/ImageExpiriment/@v.Image" data-holder-rendered="true">
                        <div class="card-body">
                            <h3>@v.Titre</h3>
                            <p class="card-text">@v.But</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    @Html.ActionLink("Afficher", "GetExpiriment", "Expiriment", new { id = v.Id }, new { @class = "btn btn-primary" })
                                    @Html.ActionLink("Favorite", "Addtofavorite", "Expiriment", new { id = v.Id }, new { @class = "btn btn-warning" })
                                </div>
                                <small class="text-muted">@v.DateTime</small>
                            </div>
                        </div>
                    </div>
                </div>
            }
        }
    </div>
</body>


    <script>
        $(function () {
            $('.slide').slick({
                slidesToShow: 3,
                slidesToScroll: 1,
                autoplay: true,


            });
        });
    </script>
    <style>
        .body.content {
            padding: 0 0 0 0;
        }
    </style>

Electronique_Labo/Views/Home/Physic.cshtml
@model Electronique_Labo.Models.ViewModel


</div>
<div class="  text-primary rounded ">

</div>

<div class=" jumbotron  mt-5">
    @*album py-5 bg-light*@
    <div class="container">
        <fieldset style="text-align: center">
            <legend class="border-bottom  border-success"><b class="text-success"> physique</b></legend>
        </fieldset>
        <div class="row">

            @foreach (var listExpiriment in Model.Expiriments)
            {
                if (listExpiriment.SecteurId == 3)
                {
            <div class="col-md-4">


                

                <div class="card mb-4 box-sizing">
                    <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x225]" style="height: 225px; width: 100%; display: block;" src="~/Images/ImageExpiriment/@listExpiriment.Image" data-holder-rendered="true">
                    <div class="card-body">
                        <h5 class="card-title">@listExpiriment.Titre</h5>
                        <p class="card-text">@listExpiriment.But</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                @Html.ActionLink("Afficher", "GetExpiriment", "Expiriment", new { id = listExpiriment.Id }, new { @class = "btn btn-primary" })
                                @Html.ActionLink(" + Favorite", "Addtofavorite", "Expiriment", new { id = listExpiriment.Id }, new { @class = "btn btn-warning  " })
                            </div>
                            <strong class="text-muted">@listExpiriment.DateTime.ToShortDateString()</strong>
                        </div>

                    </div>
                </div>

            </div>
                }
            }


        </div>
    </div>
</div>

Electronique_Labo/Views/Home/Science.cshtml
@model Electronique_Labo.Models.ViewModel


</div>
<div class="  text-primary rounded ">

</div>

<div class=" jumbotron  mt-5">
    @*album py-5 bg-light*@
    <div class="container">
        <fieldset style="text-align: center">
            <legend class="border-bottom border-primary"><b class="text-primary"> Science Expirimental</b></legend>
        </fieldset>
        <div class="row">

            @foreach (var listExpiriment in Model.Expiriments)
        {
            if (listExpiriment.SecteurId == 1)
            {
                <div class="col-md-4">

                    <div class="card mb-4 box-sizing">
                        <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x225]" style="height: 225px; width: 100%; display: block;" src="~/Images/ImageExpiriment/@listExpiriment.Image" data-holder-rendered="true">
                        <div class="card-body">
                            <h5 class="card-title">@listExpiriment.Titre</h5>
                            <p class="card-text">@listExpiriment.But</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    @Html.ActionLink("Afficher", "GetExpiriment", "Expiriment", new { id = listExpiriment.Id }, new { @class = "btn btn-primary" })
                                    @Html.ActionLink(" + Favorite", "Addtofavorite", "Expiriment", new { id = listExpiriment.Id }, new { @class = "btn btn-warning  " })
                                </div>
                                <strong class="text-muted">@listExpiriment.DateTime.ToShortDateString()</strong>
                            </div>

                        </div>
                    </div>

                </div>
        }
    }


        </div>
    </div>
</div>

Electronique_Labo/Views/Home/chimie.cshtml
@model Electronique_Labo.Models.ViewModel


</div>
<div class="  text-primary rounded ">

</div>

<div class=" jumbotron  mt-5">
    @*album py-5 bg-light*@
    <div class="container">
        <fieldset style="text-align: center">
            <legend class="border-bottom border-warning"><b class="text-warning"> Chimie</b></legend>
        </fieldset>
        <div class="row">

            @foreach (var listExpiriment in Model.Expiriments)
        {
            if (listExpiriment.SecteurId == 2)
            {
                <div class="col-md-4">




                    <div class="card mb-4 box-sizing">
                        <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x225]" style="height: 225px; width: 100%; display: block;" src="~/Images/ImageExpiriment/@listExpiriment.Image" data-holder-rendered="true">
                        <div class="card-body">
                            <h5 class="card-title">@listExpiriment.Titre</h5>
                            <p class="card-text">@listExpiriment.But</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    @Html.ActionLink("Afficher", "GetExpiriment", "Expiriment", new { id = listExpiriment.Id }, new { @class = "btn btn-primary" })
                                    @Html.ActionLink(" + Favorite", "Addtofavorite", "Expiriment", new { id = listExpiriment.Id }, new { @class = "btn btn-warning  " })
                                </div>
                                <strong class="text-muted">@listExpiriment.DateTime.ToShortDateString()</strong>
                            </div>

                        </div>
                    </div>

                </div>
        }
    }


        </div>
    </div>
</div>